name: mytasktimer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.3
  get_it: ^7.2.0
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  freezed_annotation: ^2.4.3
  json_annotation: ^4.8.1
  uuid: ^3.0.6
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.5
  freezed: ^2.5.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/Icon.png
     - assets/images/flIcon.png
